# Generated by Django 4.0.4 on 2022-05-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('info', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('info', models.TextField(max_length=10000)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.society')),
            ],
        ),
    ]
